
postgres:
  image: postgres:9.5
  container_name: "postgres"
  volumes:
    - "./postgres:/docker-entrypoint-initdb.d"
    - "./dvdrental:/dvdrental"
  environment:
    - "POSTGRES_PASSWORD=postgres"
    - "PGPASSWORD=postgres"
